# Generated by Django 5.2.1 on 2025-05-19 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('base_distance', models.DecimalField(decimal_places=2, help_text='Distance covered in base price (in KMs)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for the initial distance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_km_price', models.DecimalField(decimal_places=2, help_text='Price per additional kilometer', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('time_multiplier_1', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for first hour', max_digits=4)),
                ('time_multiplier_2', models.DecimalField(decimal_places=2, default=1.25, help_text='Multiplier for second hour', max_digits=4)),
                ('time_multiplier_3', models.DecimalField(decimal_places=2, default=2.2, help_text='Multiplier for third hour onwards', max_digits=4)),
                ('free_waiting_time', models.IntegerField(default=3, help_text='Free waiting time in minutes')),
                ('waiting_charge_per_min', models.DecimalField(decimal_places=2, help_text='Charge per minute after free waiting time', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applicable_days', models.CharField(help_text='Comma-separated days of week (0-6, Monday is 0)', max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configurations',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricingconfig')),
            ],
            options={
                'verbose_name': 'Configuration Log',
                'verbose_name_plural': 'Configuration Logs',
            },
        ),
    ]
